template-file-path: 課題1-infrastructure.yaml
parameters:
  ProjectName: aws-training
  EC2InstanceType: t3.micro
  ASGMinSize: "2"
  ASGMaxSize: "2"
  ASGDesiredSize: "2"
  CPUScaleOutThreshold: "50"
tags: {}
